### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by DennisH1978** [cinzas/homeassistant-enigma-player#16]
Hi there, I am just new with HA so please dont be so hard. I installed per HACS the components, but in the device options there is nothing to chosse for on/off, volume, notification etc. I see that i can be copied in another configuration. But where is this? what exactly is to do? I have no clue, how to fix that. Can someone help me?
That would bei great, thanks.

Greetings Dennis

**Comment by cinzas** [comment]
@DennisH1978 , I would like to help, but you're sharing to little information.

Are you sure you're using this custom_component ? Aren't you using the "standard" enigma2 integration ?

If you installed via hacs, you then need to access HomeAssistant and create the configuration file, where you specify the IP address, user and password.

Have you done that ?

Follow the instructions from the [README](https://github.com/cinzas/homeassistant-enigma-player#)

**Comment by DennisH1978** [comment]
Hello. This is what I downloaded into HACS. "Enigma2 + OpenWebIF integration - media_player and notify platforms". And I have already installed “Enigma2 (OpenWebif)”. It sounds to me in the README as if I first have to carry out the original integration of "Enigma2 (OpenWebif)" and then install the "Custom Components" via HACS. Unfortunately I don't understand where the custom components have to be inserted.

**Comment by DennisH1978** [comment]
Can you please tell me where exactly I have to write the configuration?

**Comment by cinzas** [comment]
Open a SSH connection to the host you are running homeassistant.
Locate/create your configuration.yaml file for homeassitant.



Add the configuration as follow (update your host, port,username and password with your enigma2 settings.
If you don't know how to do it, I advise you to try first to use the enigma2 integration that comes by default with HomeAssistant.

```
enigma: 
  devices:
    - host: 192.168.1.20
      port: 80
      name: Gigablue
      timeout: 20
      username: root
      password: your_password
      picon: picon

notify:
  - platform: enigma
    host: 192.168.1.20
    port: 80
    username: root
    password: your_password
    name: gigablue
```
